#!/usr/bin/env bash
# Assemble the SELF-CONTAINED install-surface scripts published to GitHub Releases (origin #2, independent
# of the artifact CDN) from the ONE verify recipe. A piped/downloaded script cannot source a sibling or read
# a sibling trust-root file, so each release asset must be a single file: this inlines
# src/span-auspex/verify-lib.sh and EMBEDS trusted_root.json (base64) so every asset shares the exact same
# recipe + anchor as the Dev Container Feature — no per-asset copy. Run in CI before uploading the assets.
#
# Emits (into the OUT dir, default dist/):
#   auspex-install.sh / .ps1       — curl|sh + irm|iex bootstrap (first-acquisition)
#   auspex-verify-gate.sh / .ps1   — MDM verify-before-install gate (AC7)
#
#   bootstrap/assemble.sh [INSTALLER_OUT]     # default INSTALLER_OUT = dist/auspex-install.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LIB="$ROOT/src/span-auspex/verify-lib.sh"
ROOT_JSON="$ROOT/src/span-auspex/trusted_root.json"
BOOT="$ROOT/bootstrap/bootstrap.sh"
BOOT_PS="$ROOT/bootstrap/bootstrap.ps1"
GATE="$ROOT/mdm/verify-gate.sh"
GATE_PS="$ROOT/mdm/verify-gate.ps1"

OUT="${1:-$ROOT/dist/auspex-install.sh}"
OUT_DIR="$(dirname "$OUT")"
OUT_PS="${OUT%.sh}.ps1"
GATE_OUT="$OUT_DIR/auspex-verify-gate.sh"
GATE_OUT_PS="$OUT_DIR/auspex-verify-gate.ps1"

for f in "$LIB" "$ROOT_JSON" "$BOOT" "$BOOT_PS" "$GATE" "$GATE_PS"; do
  [ -f "$f" ] || { echo "assemble: missing input $f" >&2; exit 1; }
done
mkdir -p "$OUT_DIR"

b64="$(base64 < "$ROOT_JSON" | tr -d '\n')"

# Emit a self-contained bash script: shared preamble (embedded trust root + inlined verify-lib.sh) followed
# by the caller-specific logic file. The single-quoted `$(…)`/`$var` (SC2016) and trailing `\`
# line-continuations (SC1003) are intentional CODEGEN — literal shell emitted into the generated asset, not
# this script's own expansion.
emit_bash() { # <logic_file> <out> <banner>
  local logic="$1" out="$2" banner="$3"
  # shellcheck disable=SC2016,SC1003
  {
    echo '#!/usr/bin/env bash'
    echo "# GENERATED by bootstrap/assemble.sh — DO NOT EDIT. ${banner}"
    echo '# Assembled from src/span-auspex/verify-lib.sh + trusted_root.json (embedded) so it shares the'
    echo '# exact verify recipe + trust anchor as the Dev Container Feature.'
    echo 'set -euo pipefail'
    echo ''
    echo '# --- embedded Sigstore trust root (origin-#2 anchor); decoded to a temp the verify lib reads ------'
    echo '_b64tmp="$(mktemp)"'
    echo "cat > \"\$_b64tmp\" <<'__AUSPEX_ROOT_B64__'"
    printf '%s\n' "$b64" | fold -w 100
    echo '__AUSPEX_ROOT_B64__'
    echo '_AUSPEX_EMBEDDED_ROOT="$(mktemp)"'
    echo 'base64 --decode < "$_b64tmp" > "$_AUSPEX_EMBEDDED_ROOT" 2>/dev/null \'
    echo '  || base64 -d < "$_b64tmp" > "$_AUSPEX_EMBEDDED_ROOT" 2>/dev/null \'
    echo '  || base64 -D < "$_b64tmp" > "$_AUSPEX_EMBEDDED_ROOT" 2>/dev/null \'
    echo '  || openssl base64 -d -A < "$_b64tmp" > "$_AUSPEX_EMBEDDED_ROOT"'
    echo 'rm -f "$_b64tmp"'
    echo 'export AUSPEX_TRUSTED_ROOT="$_AUSPEX_EMBEDDED_ROOT"'
    echo ''
    echo '# ===================== inlined src/span-auspex/verify-lib.sh ====================='
    cat "$LIB"
    echo "# ===================== inlined ${logic#"$ROOT"/} ====================="
    cat "$logic"
  } > "$out"
  chmod 0755 "$out"
  echo "assemble: wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
}

# Inject the SSOT pins + embedded trust root into a PowerShell template (its committed form carries only
# @@…@@ placeholders, so verify-lib.sh stays the single source the reconcile guard checks).
ps_pin() { sed -n "s/^$1='\\(.*\\)'\$/\\1/p" "$LIB" | head -1; }
identity="$(ps_pin COSIGN_IDENTITY_RE)"
issuer="$(ps_pin COSIGN_OIDC_ISSUER)"
cver="$(ps_pin COSIGN_VERSION)"
winsha="$(ps_pin COSIGN_SHA256_windows_amd64)"
for v in identity:"$identity" issuer:"$issuer" cver:"$cver" winsha:"$winsha"; do
  [ -n "${v#*:}" ] || { echo "assemble: could not extract ${v%%:*} from $LIB" >&2; exit 1; }
done

emit_ps() { # <template> <out>
  local template="$1" out="$2" tpl
  # Bash `${var//pat/rep}` replacement is LITERAL (no backslash/& interpretation, unlike sed) — safe for the
  # identity regex's \ ( ) . + and the base64 blob.
  tpl="$(cat "$template")"
  tpl="${tpl//@@AUSPEX_IDENTITY_RE@@/$identity}"
  tpl="${tpl//@@AUSPEX_OIDC_ISSUER@@/$issuer}"
  tpl="${tpl//@@AUSPEX_COSIGN_VERSION@@/$cver}"
  tpl="${tpl//@@AUSPEX_COSIGN_WINDOWS_AMD64_SHA@@/$winsha}"
  tpl="${tpl//@@AUSPEX_TRUSTED_ROOT_B64@@/$b64}"
  if printf '%s' "$tpl" | grep -q '@@AUSPEX_'; then
    echo "assemble: unsubstituted @@…@@ placeholder remains in $out" >&2
    exit 1
  fi
  printf '%s\n' "$tpl" > "$out"
  echo "assemble: wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
}

emit_bash "$BOOT" "$OUT"      "Self-contained auspex installer for GitHub Releases (origin #2)."
emit_bash "$GATE" "$GATE_OUT" "Self-contained auspex MDM verify-before-install gate (AC7)."
emit_ps   "$BOOT_PS" "$OUT_PS"
emit_ps   "$GATE_PS" "$GATE_OUT_PS"

# Cursor cloud recipe scripts (src/cursor-cloud/) — staged into dist/ so the Release signs + ships them as
# first-class assets (parity with the Dev Container Feature). Unlike the installers above they need NO
# assembly: they carry no inlined verify recipe or trust root — the binary fetch DELEGATES to the signed
# auspex-install.sh bootstrap (which self-verifies against the embedded anchor). So they are copied verbatim
# from source, published under a cursor-cloud- prefix, and consumed from releases/latest/download/.
CC_SRC="$ROOT/src/cursor-cloud"
for s in install start preflight; do
  src="$CC_SRC/$s.sh"
  [ -f "$src" ] || { echo "assemble: missing input $src" >&2; exit 1; }
  dst="$OUT_DIR/cursor-cloud-$s.sh"
  cp "$src" "$dst"
  chmod 0755 "$dst"
  echo "assemble: wrote $dst ($(wc -c < "$dst" | tr -d ' ') bytes)"
done
